// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/otp/type/otp.proto

package otp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReq) Reset() {
	*x = SendReq{}
	mi := &file_proto_otp_type_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReq) ProtoMessage() {}

func (x *SendReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_type_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReq.ProtoReflect.Descriptor instead.
func (*SendReq) Descriptor() ([]byte, []int) {
	return file_proto_otp_type_otp_proto_rawDescGZIP(), []int{0}
}

func (x *SendReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type VerifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyReq) Reset() {
	*x = VerifyReq{}
	mi := &file_proto_otp_type_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReq) ProtoMessage() {}

func (x *VerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_type_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReq.ProtoReflect.Descriptor instead.
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return file_proto_otp_type_otp_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyReq) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type VerifyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRes) Reset() {
	*x = VerifyRes{}
	mi := &file_proto_otp_type_otp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRes) ProtoMessage() {}

func (x *VerifyRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_type_otp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRes.ProtoReflect.Descriptor instead.
func (*VerifyRes) Descriptor() ([]byte, []int) {
	return file_proto_otp_type_otp_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRes) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_otp_type_otp_proto protoreflect.FileDescriptor

const file_proto_otp_type_otp_proto_rawDesc = "" +
	"\n" +
	"\x18proto/otp/type/otp.proto\x12\botp.type\"\x1f\n" +
	"\aSendReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"3\n" +
	"\tVerifyReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"!\n" +
	"\tVerifyRes\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05validB1Z/github.com/faujiahmat/zentra-proto/protogen/otpb\x06proto3"

var (
	file_proto_otp_type_otp_proto_rawDescOnce sync.Once
	file_proto_otp_type_otp_proto_rawDescData []byte
)

func file_proto_otp_type_otp_proto_rawDescGZIP() []byte {
	file_proto_otp_type_otp_proto_rawDescOnce.Do(func() {
		file_proto_otp_type_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_otp_type_otp_proto_rawDesc), len(file_proto_otp_type_otp_proto_rawDesc)))
	})
	return file_proto_otp_type_otp_proto_rawDescData
}

var file_proto_otp_type_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_otp_type_otp_proto_goTypes = []any{
	(*SendReq)(nil),   // 0: otp.type.SendReq
	(*VerifyReq)(nil), // 1: otp.type.VerifyReq
	(*VerifyRes)(nil), // 2: otp.type.VerifyRes
}
var file_proto_otp_type_otp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_otp_type_otp_proto_init() }
func file_proto_otp_type_otp_proto_init() {
	if File_proto_otp_type_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_otp_type_otp_proto_rawDesc), len(file_proto_otp_type_otp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_otp_type_otp_proto_goTypes,
		DependencyIndexes: file_proto_otp_type_otp_proto_depIdxs,
		MessageInfos:      file_proto_otp_type_otp_proto_msgTypes,
	}.Build()
	File_proto_otp_type_otp_proto = out.File
	file_proto_otp_type_otp_proto_goTypes = nil
	file_proto_otp_type_otp_proto_depIdxs = nil
}
