// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/user/type/register_request.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_proto_user_type_register_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_register_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_user_type_register_request_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,proto3" json:"full_name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_proto_user_type_register_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_register_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_user_type_register_request_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_proto_user_type_register_request_proto protoreflect.FileDescriptor

const file_proto_user_type_register_request_proto_rawDesc = "" +
	"\n" +
	"&proto/user/type/register_request.proto\x12\tuser.type\"\x1d\n" +
	"\x05Email\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"w\n" +
	"\vRegisterReq\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\tR\auser_id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tfull_name\x18\x03 \x01(\tR\tfull_name\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpasswordB2Z0github.com/faujiahmat/zentra-proto/protogen/userb\x06proto3"

var (
	file_proto_user_type_register_request_proto_rawDescOnce sync.Once
	file_proto_user_type_register_request_proto_rawDescData []byte
)

func file_proto_user_type_register_request_proto_rawDescGZIP() []byte {
	file_proto_user_type_register_request_proto_rawDescOnce.Do(func() {
		file_proto_user_type_register_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_type_register_request_proto_rawDesc), len(file_proto_user_type_register_request_proto_rawDesc)))
	})
	return file_proto_user_type_register_request_proto_rawDescData
}

var file_proto_user_type_register_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_type_register_request_proto_goTypes = []any{
	(*Email)(nil),       // 0: user.type.Email
	(*RegisterReq)(nil), // 1: user.type.RegisterReq
}
var file_proto_user_type_register_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_type_register_request_proto_init() }
func file_proto_user_type_register_request_proto_init() {
	if File_proto_user_type_register_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_type_register_request_proto_rawDesc), len(file_proto_user_type_register_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_type_register_request_proto_goTypes,
		DependencyIndexes: file_proto_user_type_register_request_proto_depIdxs,
		MessageInfos:      file_proto_user_type_register_request_proto_msgTypes,
	}.Build()
	File_proto_user_type_register_request_proto = out.File
	file_proto_user_type_register_request_proto_goTypes = nil
	file_proto_user_type_register_request_proto_depIdxs = nil
}
