// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/user/service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_user_service_proto protoreflect.FileDescriptor

const file_proto_user_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/user/service.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\"proto/user/type/login_google.proto\x1a&proto/user/type/register_request.proto\x1a\x1bproto/user/type/token.proto\x1a\x1aproto/user/type/user.proto2\x9f\x03\n" +
	"\vUserService\x12:\n" +
	"\x06Create\x12\x16.user.type.RegisterReq\x1a\x16.google.protobuf.Empty\"\x00\x129\n" +
	"\vFindByEmail\x12\x10.user.type.Email\x1a\x16.user.type.FindUserRes\"\x00\x12G\n" +
	"\x12FindByRefreshToken\x12\x17.user.type.RefreshToken\x1a\x16.user.type.FindUserRes\"\x00\x12:\n" +
	"\x06Upsert\x12\x1d.user.type.LoginWithGoogleReq\x1a\x0f.user.type.User\"\x00\x12J\n" +
	"\x0fAddRefreshToken\x12\x1d.user.type.AddRefreshTokenReq\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x13SetNullRefreshToken\x12\x17.user.type.RefreshToken\x1a\x16.google.protobuf.Empty\"\x00B2Z0github.com/faujiahmat/zentra-proto/protogen/userb\x06proto3"

var file_proto_user_service_proto_goTypes = []any{
	(*RegisterReq)(nil),        // 0: user.type.RegisterReq
	(*Email)(nil),              // 1: user.type.Email
	(*RefreshToken)(nil),       // 2: user.type.RefreshToken
	(*LoginWithGoogleReq)(nil), // 3: user.type.LoginWithGoogleReq
	(*AddRefreshTokenReq)(nil), // 4: user.type.AddRefreshTokenReq
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
	(*FindUserRes)(nil),        // 6: user.type.FindUserRes
	(*User)(nil),               // 7: user.type.User
}
var file_proto_user_service_proto_depIdxs = []int32{
	0, // 0: user.UserService.Create:input_type -> user.type.RegisterReq
	1, // 1: user.UserService.FindByEmail:input_type -> user.type.Email
	2, // 2: user.UserService.FindByRefreshToken:input_type -> user.type.RefreshToken
	3, // 3: user.UserService.Upsert:input_type -> user.type.LoginWithGoogleReq
	4, // 4: user.UserService.AddRefreshToken:input_type -> user.type.AddRefreshTokenReq
	2, // 5: user.UserService.SetNullRefreshToken:input_type -> user.type.RefreshToken
	5, // 6: user.UserService.Create:output_type -> google.protobuf.Empty
	6, // 7: user.UserService.FindByEmail:output_type -> user.type.FindUserRes
	6, // 8: user.UserService.FindByRefreshToken:output_type -> user.type.FindUserRes
	7, // 9: user.UserService.Upsert:output_type -> user.type.User
	5, // 10: user.UserService.AddRefreshToken:output_type -> google.protobuf.Empty
	5, // 11: user.UserService.SetNullRefreshToken:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_service_proto_init() }
func file_proto_user_service_proto_init() {
	if File_proto_user_service_proto != nil {
		return
	}
	file_proto_user_type_login_google_proto_init()
	file_proto_user_type_register_request_proto_init()
	file_proto_user_type_token_proto_init()
	file_proto_user_type_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_service_proto_rawDesc), len(file_proto_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_service_proto_goTypes,
		DependencyIndexes: file_proto_user_service_proto_depIdxs,
	}.Build()
	File_proto_user_service_proto = out.File
	file_proto_user_service_proto_goTypes = nil
	file_proto_user_service_proto_depIdxs = nil
}
