// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/user/type/token.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_proto_user_type_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_proto_user_type_token_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AddRefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRefreshTokenReq) Reset() {
	*x = AddRefreshTokenReq{}
	mi := &file_proto_user_type_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRefreshTokenReq) ProtoMessage() {}

func (x *AddRefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRefreshTokenReq.ProtoReflect.Descriptor instead.
func (*AddRefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_proto_user_type_token_proto_rawDescGZIP(), []int{1}
}

func (x *AddRefreshTokenReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddRefreshTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_user_type_token_proto protoreflect.FileDescriptor

const file_proto_user_type_token_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/user/type/token.proto\x12\tuser.type\"$\n" +
	"\fRefreshToken\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"@\n" +
	"\x12AddRefreshTokenReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05tokenB2Z0github.com/faujiahmat/zentra-proto/protogen/userb\x06proto3"

var (
	file_proto_user_type_token_proto_rawDescOnce sync.Once
	file_proto_user_type_token_proto_rawDescData []byte
)

func file_proto_user_type_token_proto_rawDescGZIP() []byte {
	file_proto_user_type_token_proto_rawDescOnce.Do(func() {
		file_proto_user_type_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_type_token_proto_rawDesc), len(file_proto_user_type_token_proto_rawDesc)))
	})
	return file_proto_user_type_token_proto_rawDescData
}

var file_proto_user_type_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_type_token_proto_goTypes = []any{
	(*RefreshToken)(nil),       // 0: user.type.RefreshToken
	(*AddRefreshTokenReq)(nil), // 1: user.type.AddRefreshTokenReq
}
var file_proto_user_type_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_type_token_proto_init() }
func file_proto_user_type_token_proto_init() {
	if File_proto_user_type_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_type_token_proto_rawDesc), len(file_proto_user_type_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_type_token_proto_goTypes,
		DependencyIndexes: file_proto_user_type_token_proto_depIdxs,
		MessageInfos:      file_proto_user_type_token_proto_msgTypes,
	}.Build()
	File_proto_user_type_token_proto = out.File
	file_proto_user_type_token_proto_goTypes = nil
	file_proto_user_type_token_proto_depIdxs = nil
}
