// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/order/type/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddShippingIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=product_id,proto3" json:"order_id,omitempty"`
	ShippingId    string                 `protobuf:"bytes,2,opt,name=shipping_id,proto3" json:"shipping_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShippingIdReq) Reset() {
	*x = AddShippingIdReq{}
	mi := &file_proto_order_type_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShippingIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShippingIdReq) ProtoMessage() {}

func (x *AddShippingIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_type_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShippingIdReq.ProtoReflect.Descriptor instead.
func (*AddShippingIdReq) Descriptor() ([]byte, []int) {
	return file_proto_order_type_order_proto_rawDescGZIP(), []int{0}
}

func (x *AddShippingIdReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AddShippingIdReq) GetShippingId() string {
	if x != nil {
		return x.ShippingId
	}
	return ""
}

type UpdateStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=product_id,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusReq) Reset() {
	*x = UpdateStatusReq{}
	mi := &file_proto_order_type_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReq) ProtoMessage() {}

func (x *UpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_type_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_proto_order_type_order_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatusReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_order_type_order_proto protoreflect.FileDescriptor

const file_proto_order_type_order_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/order/type/order.proto\x12\n" +
	"order.type\"R\n" +
	"\x10AddShippingIdReq\x12\x1c\n" +
	"\border_id\x18\x01 \x01(\tR\n" +
	"product_id\x12 \n" +
	"\vshipping_id\x18\x02 \x01(\tR\vshipping_id\"G\n" +
	"\x0fUpdateStatusReq\x12\x1c\n" +
	"\border_id\x18\x01 \x01(\tR\n" +
	"product_id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06statusB3Z1github.com/faujiahmat/zentra-proto/protogen/orderb\x06proto3"

var (
	file_proto_order_type_order_proto_rawDescOnce sync.Once
	file_proto_order_type_order_proto_rawDescData []byte
)

func file_proto_order_type_order_proto_rawDescGZIP() []byte {
	file_proto_order_type_order_proto_rawDescOnce.Do(func() {
		file_proto_order_type_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_type_order_proto_rawDesc), len(file_proto_order_type_order_proto_rawDesc)))
	})
	return file_proto_order_type_order_proto_rawDescData
}

var file_proto_order_type_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_order_type_order_proto_goTypes = []any{
	(*AddShippingIdReq)(nil), // 0: order.type.AddShippingIdReq
	(*UpdateStatusReq)(nil),  // 1: order.type.UpdateStatusReq
}
var file_proto_order_type_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_type_order_proto_init() }
func file_proto_order_type_order_proto_init() {
	if File_proto_order_type_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_type_order_proto_rawDesc), len(file_proto_order_type_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_order_type_order_proto_goTypes,
		DependencyIndexes: file_proto_order_type_order_proto_depIdxs,
		MessageInfos:      file_proto_order_type_order_proto_msgTypes,
	}.Build()
	File_proto_order_type_order_proto = out.File
	file_proto_order_type_order_proto_goTypes = nil
	file_proto_order_type_order_proto_depIdxs = nil
}
