// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/order/service.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_order_service_proto protoreflect.FileDescriptor

const file_proto_order_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/order/service.proto\x12\x05order\x1a\x1cproto/order/type/order.proto\x1a\x1bgoogle/protobuf/empty.proto2\x9e\x01\n" +
	"\fOrderService\x12G\n" +
	"\rAddShippingId\x12\x1c.order.type.AddShippingIdReq\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\fUpdateStatus\x12\x1b.order.type.UpdateStatusReq\x1a\x16.google.protobuf.Empty\"\x00B3Z1github.com/faujiahmat/zentra-proto/protogen/orderb\x06proto3"

var file_proto_order_service_proto_goTypes = []any{
	(*AddShippingIdReq)(nil), // 0: order.type.AddShippingIdReq
	(*UpdateStatusReq)(nil),  // 1: order.type.UpdateStatusReq
	(*emptypb.Empty)(nil),    // 2: google.protobuf.Empty
}
var file_proto_order_service_proto_depIdxs = []int32{
	0, // 0: order.OrderService.AddShippingId:input_type -> order.type.AddShippingIdReq
	1, // 1: order.OrderService.UpdateStatus:input_type -> order.type.UpdateStatusReq
	2, // 2: order.OrderService.AddShippingId:output_type -> google.protobuf.Empty
	2, // 3: order.OrderService.UpdateStatus:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_service_proto_init() }
func file_proto_order_service_proto_init() {
	if File_proto_order_service_proto != nil {
		return
	}
	file_proto_order_type_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_service_proto_rawDesc), len(file_proto_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_service_proto_goTypes,
		DependencyIndexes: file_proto_order_service_proto_depIdxs,
	}.Build()
	File_proto_order_service_proto = out.File
	file_proto_order_service_proto_goTypes = nil
	file_proto_order_service_proto_depIdxs = nil
}
