// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/product/type/cart.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductCart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,proto3" json:"product_name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Price         uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         uint32                 `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Length        uint32                 `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	Width         uint32                 `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float32                `protobuf:"fixed32,9,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCart) Reset() {
	*x = ProductCart{}
	mi := &file_proto_product_type_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCart) ProtoMessage() {}

func (x *ProductCart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_type_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCart.ProtoReflect.Descriptor instead.
func (*ProductCart) Descriptor() ([]byte, []int) {
	return file_proto_product_type_cart_proto_rawDescGZIP(), []int{0}
}

func (x *ProductCart) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductCart) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductCart) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductCart) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductCart) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductCart) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ProductCart) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ProductCart) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProductCart) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ProductsCartRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductCart         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsCartRes) Reset() {
	*x = ProductsCartRes{}
	mi := &file_proto_product_type_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsCartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsCartRes) ProtoMessage() {}

func (x *ProductsCartRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_type_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsCartRes.ProtoReflect.Descriptor instead.
func (*ProductsCartRes) Descriptor() ([]byte, []int) {
	return file_proto_product_type_cart_proto_rawDescGZIP(), []int{1}
}

func (x *ProductsCartRes) GetData() []*ProductCart {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_product_type_cart_proto protoreflect.FileDescriptor

const file_proto_product_type_cart_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/product/type/cart.proto\x12\fproduct.type\"\xf1\x01\n" +
	"\vProductCart\x12\x1e\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\n" +
	"product_id\x12\"\n" +
	"\fproduct_name\x18\x02 \x01(\tR\fproduct_name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\rR\x05stock\x12\x16\n" +
	"\x06length\x18\x06 \x01(\rR\x06length\x12\x14\n" +
	"\x05width\x18\a \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\rR\x06height\x12\x16\n" +
	"\x06weight\x18\t \x01(\x02R\x06weight\"@\n" +
	"\x0fProductsCartRes\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.product.type.ProductCartR\x04dataB5Z3github.com/faujiahmat/zentra-proto/protogen/productb\x06proto3"

var (
	file_proto_product_type_cart_proto_rawDescOnce sync.Once
	file_proto_product_type_cart_proto_rawDescData []byte
)

func file_proto_product_type_cart_proto_rawDescGZIP() []byte {
	file_proto_product_type_cart_proto_rawDescOnce.Do(func() {
		file_proto_product_type_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_type_cart_proto_rawDesc), len(file_proto_product_type_cart_proto_rawDesc)))
	})
	return file_proto_product_type_cart_proto_rawDescData
}

var file_proto_product_type_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_product_type_cart_proto_goTypes = []any{
	(*ProductCart)(nil),     // 0: product.type.ProductCart
	(*ProductsCartRes)(nil), // 1: product.type.ProductsCartRes
}
var file_proto_product_type_cart_proto_depIdxs = []int32{
	0, // 0: product.type.ProductsCartRes.data:type_name -> product.type.ProductCart
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_product_type_cart_proto_init() }
func file_proto_product_type_cart_proto_init() {
	if File_proto_product_type_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_type_cart_proto_rawDesc), len(file_proto_product_type_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_product_type_cart_proto_goTypes,
		DependencyIndexes: file_proto_product_type_cart_proto_depIdxs,
		MessageInfos:      file_proto_product_type_cart_proto_msgTypes,
	}.Build()
	File_proto_product_type_cart_proto = out.File
	file_proto_product_type_cart_proto_goTypes = nil
	file_proto_product_type_cart_proto_depIdxs = nil
}
